---
sudo: required
dist: bionic
language: minimal
before_install:
  - |
    curl -Os https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb
    curl -Os https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_SHA256SUMS
    curl -Os https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_SHA256SUMS.sig
    gpg --receive-key 51852D87348FFC4C
    gpg --verify vagrant_2.2.14_SHA256SUMS.sig vagrant_2.2.14_SHA256SUMS
    sha256sum -c vagrant_2.2.14_SHA256SUMS 2>&1 | grep OK
    sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
    sudo dpkg -i vagrant_2.2.14_x86_64.deb
    sudo vagrant plugin install vagrant-libvirt
  - |
    sudo apt-get -y purge python3-openssl && sudo apt-get -y autoremove
    sudo apt-get update && sudo apt-get install -y ca-certificates curl gcc iproute2 python3 python3-dev sudo
    curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3
    sudo pip install tox
script:
  - sudo tox -e ci
