---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    roles-path: roles
driver:
  name: vagrant
  provider:
    name: libvirt
lint:
  name: yamllint
platforms:
  - name: master
    box: generic/ubuntu1604
    cpu: 1
    memory: 1024
    interfaces:
      - auto_config: true
        network_name: private_network
        ip: "192.168.99.20"
    provider_raw_config_args:
      - 'nic_model_type = "virtio"'
      - 'disk_bus = "virtio"'
      - 'volume_cache = "none"'
      - 'storage :file, bus: "virtio", cache: "none"'
    groups:
      - k3s-master
      - all
  - name: agent1
    box: generic/ubuntu1604
    cpu: 1
    memory: 1024
    interfaces:
      - auto_config: true
        network_name: private_network
        ip: "192.168.99.30"
    provider_raw_config_args:
      - 'nic_model_type = "virtio"'
      - 'disk_bus = "virtio"'
      - 'volume_cache = "none"'
      - 'storage :file, bus: "virtio", cache: "none"'
    groups:
      - k3s-agent
      - all
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  env:
    ANSIBLE_ROLES_PATH: ${PWD}/roles
  config_options:
    defaults:
      forks: 20
    ssh_connection:
      pipelining: true
      ssh_args: -o ControlMaster=auto -o ControlPersist=600s
  playbooks:
    converge: ../../k3s-cluster.yml
  inventory:
    links:
      group_vars: ../../inventories/molecule/group_vars
scenario:
  name: default
verifier:
  name: testinfra
  options:
    junit-xml: report.xml
  lint:
    name: flake8
